url: https://geni.code-maven.com
repo: https://github.com/szabgab/geni.com.rs
branch: main
site_name: Geni RUST API
link_to_source: true
footer: The Geni RUST API
tags:
  title: Tags
  description: Geni Rust API
from:
  name: Gabor Szabo
  email: gabor@szabgab.com
archive:
  title: Archive
  description: List of all the articles

authors:
  - name: Gabor Szabo
    nickname: szabgab
    picture: szabgab.png

navbar:
  start:
    - path: /
      title: Home
  end:
    - path: /about
      title: About

