name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check format
      run: cargo fmt --check
    - name: Check clippy
      run: cargo clippy -- --deny warnings
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose

